name: Run Basic Tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Instalar dependencias do projeto
        uses: npm install


      - name: Run Cypress Tests
        uses: cypress-io/github-action@v7

        with:
          record: true

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      #upload do relatório do mocha
      - name: upload relatório
        uses: actions/upload-artifact@v3
        with:
          name: Relatório
          path: cypress/reports/html
